#!/usr/bin/env python3
"""Alimente communal/*.json à partir de _index.json et d'événements spécifiques."""

from __future__ import annotations

import json
from pathlib import Path

COMMUNAL_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "histoire" / "faits" / "communal"


def _evt(
    *,
    categorie: str,
    debut: str,
    fin: str,
    libelle: str,
    description: str,
    commune: str,
    departement: str | None,
    region: str | None,
) -> dict:
    return {
        "type": "COMMUNAL",
        "categorie": categorie,
        "debut": debut,
        "fin": fin,
        "libelle": libelle,
        "description": description,
        "commune": commune,
        "departement": departement,
        "region": region,
    }


ESTUAIRE_SLUGS = {
    "prinquiau", "besne", "la_chapelle_launay", "pontchateau", "campbon",
    "savenay", "crossac", "bouvron", "lavau_sur_loire", "donges", "missillac",
    "lusanger",
}


def _concordat(*, commune: str, dept: str | None, region: str | None, diocese: str) -> dict:
    return _evt(
        categorie="CULTURE", debut="1801", fin="1801",
        libelle=f"Concordat et diocèse de {diocese}",
        description=f"Après le Concordat, la paroisse est rattachée au diocèse de {diocese}.",
        commune=commune, departement=dept, region=region,
    )


def _pandemies(*, commune: str, dept: str | None, region: str | None) -> list[dict]:
    return [
        _evt(
            categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
            description="La commune subit la seconde grande vague de choléra, comme l'ensemble du département.",
            commune=commune, departement=dept, region=region,
        ),
        _evt(
            categorie="PANDEMIE", debut="1870", fin="1871", libelle="Épidémie de variole",
            description="Recrudescence des maladies infectieuses pendant la guerre franco-prussienne.",
            commune=commune, departement=dept, region=region,
        ),
    ]


def _modernisation(*, commune: str, dept: str | None, region: str | None) -> dict:
    return _evt(
        categorie="SCIENCE", debut="1900", fin="1970", libelle="Modernisation rurale",
        description="Électrification progressive, voirie, scolarisation et mécanisation agricole.",
        commune=commune, departement=dept, region=region,
    )


def _poche_saint_nazaire(*, commune: str, dept: str | None, region: str | None) -> dict:
    return _evt(
        categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
        description="La commune reste dans la poche allemande de Saint-Nazaire jusqu'au 11 mai 1945.",
        commune=commune, departement=dept, region=region,
    )


def base_events(meta: dict) -> list[dict]:
    commune = meta["commune"]
    dept = meta.get("departement")
    region = meta.get("region")
    slug = meta["slug"]
    events = [
        _evt(
            categorie="ADMINISTRATION",
            debut="1790",
            fin="1790",
            libelle=f"Création de la commune de {commune}",
            description="Réorganisation communale de la Révolution française.",
            commune=commune,
            departement=dept,
            region=region,
        ),
    ]

    if dept == "Morbihan":
        events.extend(
            [
                _evt(
                    categorie="GUERRE",
                    debut="1793",
                    fin="1800",
                    libelle="Chouannerie dans la paroisse",
                    description="Mobilisation royaliste dans les campagnes du Morbihan.",
                    commune=commune,
                    departement=dept,
                    region=region,
                ),
                _concordat(commune=commune, dept=dept, region=region, diocese="Vannes"),
                *_pandemies(commune=commune, dept=dept, region=region),
                _modernisation(commune=commune, dept=dept, region=region),
                _evt(
                    categorie="GUERRE",
                    debut="1940",
                    fin="1944",
                    libelle="Seconde Guerre mondiale et Occupation",
                    description="Réquisitions, contraintes et résistance locale.",
                    commune=commune,
                    departement=dept,
                    region=region,
                ),
                _evt(
                    categorie="EVENEMENT",
                    debut="1944",
                    fin="1944",
                    libelle="Libération (été 1944)",
                    description="Fin de l'Occupation dans la commune.",
                    commune=commune,
                    departement=dept,
                    region=region,
                ),
            ]
        )
    elif dept in {"Ille-Et-Vilaine", "Loire-Atlantique"}:
        events.extend(
            [
                _evt(
                    categorie="GUERRE",
                    debut="1793",
                    fin="1796",
                    libelle="Guerres civiles de l'Ouest",
                    description="Chouannerie ou guerre de Vendée selon les secteurs.",
                    commune=commune,
                    departement=dept,
                    region=region,
                ),
                _concordat(commune=commune, dept=dept, region=region, diocese="Nantes"),
                *_pandemies(commune=commune, dept=dept, region=region),
                _modernisation(commune=commune, dept=dept, region=region),
                _evt(
                    categorie="GUERRE",
                    debut="1940",
                    fin="1944",
                    libelle="Seconde Guerre mondiale",
                    description="Occupation ou zone libre selon la période ; résistance locale.",
                    commune=commune,
                    departement=dept,
                    region=region,
                ),
            ]
        )
        if slug in ESTUAIRE_SLUGS:
            events.append(_poche_saint_nazaire(commune=commune, dept=dept, region=region))
    elif dept == "Paris":
        events.extend(
            [
                _evt(
                    categorie="EVENEMENT",
                    debut="1871",
                    fin="1871",
                    libelle="Commune de Paris",
                    description="Paris au cœur de l'insurrection de 1871.",
                    commune=commune,
                    departement=dept,
                    region=region,
                ),
                _evt(
                    categorie="GUERRE",
                    debut="1940",
                    fin="1944",
                    libelle="Occupation allemande",
                    description="Occupation de Paris pendant la Seconde Guerre mondiale.",
                    commune=commune,
                    departement=dept,
                    region=region,
                ),
            ]
        )

    return events


# Événements spécifiques (slug → liste complète ou additions remplaçant le générique)
CUSTOM: dict[str, list[dict]] = {
    "besne": [
        _evt(categorie="CULTURE", debut="0500", fin="0600", libelle="Ermites Friard et Secondel",
             description="Vinduneta Insula ; évangélisation par les saints Friard et Secondel, patrons de la paroisse.",
             commune="Besné", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Besné",
             description="Commune du pays nantais, au cœur de la Brière.", commune="Besné",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="POLITIQUE", debut="1793-03-13", fin="1793-03-13", libelle="Révolte contre la conscription",
             description="La population refuse la levée en masse et manifeste son opposition à la Révolution.",
             commune="Besné", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="CULTURE", debut="1887", fin="1893", libelle="Construction de l'église Saint-Friard",
             description="L'ancienne église est remplacée ; crypte avec sarcophages mérovingiens de Friard et Secondel.",
             commune="Besné", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="SCIENCE", debut="1850", fin="1950", libelle="Dessèchement des marais et industries",
             description="Achèvement du dessèchement, raffinerie de betteraves et carrières de granit.",
             commune="Besné", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Besné",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et contraintes dans la commune.", commune="Besné",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="Besné reste dans la poche allemande jusqu'au 11 mai 1945.", commune="Besné",
             departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
    "augan": [
        _evt(categorie="POLITIQUE", debut="1532", fin="1532", libelle="Rattachement de la Bretagne au royaume de France",
             description="Augan devient définitivement une paroisse du royaume de France.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1595", fin="1595", libelle="Guerres de Religion",
             description="Destruction du presbytère de Primeterre et du château de Gerguy.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1789", fin="1789", libelle="Cahier de doléances",
             description="La paroisse adopte les revendications de Ploërmel sans rédiger de cahier propre.",
             commune="Augan", departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1790-01-18", fin="1790-02-05", libelle="Émeutes paysannes",
             description="Attaques des châteaux du Bois-du-Loup et de la Grée de Callac ; destruction de titres féodaux.",
             commune="Augan", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune d'Augan",
             description="Création officielle de la commune et mise en place du conseil municipal.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1790-02-21", fin="1790-02-21", libelle="Élection du premier maire",
             description="Pierre Eono, boulanger, est élu premier maire d'Augan.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1790", fin="1791", libelle="Refus de serment du recteur Joseph Trillard",
             description="Le recteur refuse la Constitution civile du clergé et entre en clandestinité.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1792", fin="1792", libelle="Occupation du bourg",
             description="Troupes révolutionnaires occupent le bourg lors du recouvrement forcé des impôts.",
             commune="Augan", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie morbihannaise",
             description="Participation active ; plusieurs habitants rejoignent les insurgés royalistes.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1794-03-11", fin="1794-03-11", libelle="Exécution du vicaire Joseph Pongérard",
             description="Joseph Pongérard est exécuté à Rennes ; plusieurs chapelles d'Augan sont détruites.",
             commune="Augan", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1801", fin="1801", libelle="Concordat",
             description="Rétablissement de l'organisation religieuse ; la paroisse retrouve un fonctionnement normal.",
             commune="Augan", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1836", fin="1836", libelle="Cession de territoire à Monteneuf",
             description="Une partie du territoire communal est cédée à Monteneuf.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1843", fin="1843", libelle="Création de la paroisse de Porcaro",
             description="Nouvelle paroisse créée à partir d'une partie du territoire d'Augan.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="Grave épidémie ; près d'une centaine de victimes dans la commune.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1854", fin="1854", libelle="Épidémie de dysenterie",
             description="Épidémie de dysenterie touchant la commune.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1859", fin="1860", libelle="Création de la commune de Porcaro",
             description="Augan perd plusieurs villages et une partie importante de son territoire.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1868", fin="1868", libelle="Démolition de l'église Saint-Marc",
             description="Monnaies médiévales découvertes (fondation vers 1150) ; construction de l'église actuelle.",
             commune="Augan", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1870", fin="1871", libelle="Guerre franco-prussienne",
             description="Mobilisation des habitants de la commune.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1870", fin="1871", libelle="Épidémie de variole",
             description="Épidémie pendant la guerre franco-prussienne.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1873", fin="1873", libelle="Extension du camp de Coëtquidan",
             description="Début de l'extension du camp militaire influençant le nord-est de la commune.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1876", fin="1876", libelle="Construction de la mairie-école",
             description="Futur siège de la municipalité ; école de garçons.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1882", fin="1950", libelle="Passage du Tacot du Morbihan",
             description="Ligne à voie étroite Ploërmel–Surzur ; desserte des bourgs voisins.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1900", fin="1900", libelle="Expropriations pour Coëtquidan",
             description="568 hectares et le château du Bois-du-Loup expropriés pour l'agrandissement du camp.",
             commune="Augan", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1914", fin="1918", libelle="Première Guerre mondiale",
             description="Nombreux habitants tués au front ; noms inscrits au monument aux morts.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1931-04", fin="1931-04", libelle="Électrification du bourg",
             description="Mise en service de l'électricité dans le bourg (fin avril 1931).", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1939", fin="1944", libelle="Occupation allemande",
             description="Occupation allemande pendant la Seconde Guerre mondiale.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="EVENEMENT", debut="1944", fin="1944", libelle="Libération de la commune",
             description="Libération après les combats de l'été en Bretagne.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1969-04", fin="1969-04", libelle="Réseau d'eau potable",
             description="Mise en service du réseau (Syndicat de Monteneuf), à Pâques 1969.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1970", fin="1980", libelle="Remembrement agricole",
             description="Remembrement et modernisation de l'exploitation des terres.", commune="Augan",
             departement="Morbihan", region="Bretagne"),
    ],
    "pluherlin": [
        _evt(categorie="CULTURE", debut="1500", fin="1500", libelle="Châtellenie de Rochefort",
             description="La paroisse dépend de Rochefort ; seigneuries de Talhouët, Trébrun, Boisbréhan et Pont-au-Roux.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1500", fin="1599", libelle="Agriculture et habitat dispersé",
             description="Exploitation par métairies ; villages et manoirs dispersés sur le territoire.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1588", fin="1588", libelle="Chronogramme de la Renaissance",
             description="Plus ancien chronogramme conservé sur une maison ou ferme de la commune.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1600", fin="1699", libelle="Fermes et manoirs du XVIIe siècle",
             description="Construction ou remaniement de nombreux bâtiments, dont plusieurs datés 1644, 1657 et 1679.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1700", fin="1900", libelle="Hameaux de Kerempifre / Kerampiffe",
             description="Fermes et hameaux cités dans les registres (bois Guillemot, bourg).",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1778", fin="1778", libelle="Description par Jean-Baptiste Ogée",
             description="La paroisse est décrite comme une importante communauté rurale des Landes de Lanvaux.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1789", fin="1789", libelle="Cahier de doléances",
             description="Rédaction du cahier de doléances dans le contexte de la Révolution française.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Pluherlin",
             description="Érection de Pluherlin en commune lors de la création des communes françaises.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Réaction aux réquisitions, pillages et arrestations ; armoiries martelées, traditions locales.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1802", fin="1802", libelle="Réorganisation religieuse du Concordat",
             description="La commune est amputée d'une partie de son territoire (ancienne trêve paroissiale).",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1830", fin="1900", libelle="Carrières d'ardoise",
             description="Développement des carrières (Pont aux Roux, Croix aux Chênes, Pont de l'Église, La Grée Pouté…).",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1835", fin="1835", libelle="Premier instituteur",
             description="Premier instituteur attesté ; la mairie accueille l'école des garçons.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1853", fin="1853", libelle="Description de Marteville et Varin",
             description="Publication d'une description détaillée de la commune, de son agriculture et de ses villages.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1882", fin="1950", libelle="Gare du Tacot à Pluherlin",
             description="La commune est desservie par le chemin de fer du Morbihan.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1886", fin="1886", libelle="École des garçons insalubre",
             description="Le Conseil général juge l'école trop exiguë ; décision de construire un nouvel établissement.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1887", fin="1887", libelle="Nouvelle école et église paroissiale",
             description="École des garçons (architecte Le Ray) et construction de l'église actuelle.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1891", fin="1891", libelle="Fermeture de la carrière de la Croix aux Chênes",
             description="Fin de l'exploitation de la carrière d'ardoise.", commune="Pluherlin",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1902", fin="1902", libelle="Fermeture de la carrière du Pont de l'Église",
             description="Fermeture définitive ; tentatives de réouverture en 1914 puis en 1970.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1905", fin="1905", libelle="Séparation des Églises et de l'État",
             description="Réorganisation de l'enseignement confessionnel.", commune="Pluherlin",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1907", fin="1907", libelle="École libre Saint-Gentien",
             description="Construction de l'école libre Saint-Gentien.", commune="Pluherlin",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1911-06-14", fin="1911-06-14", libelle="Biens de la fabrique paroissiale",
             description="Décret présidentiel attribuant à la commune les biens de l'ancienne fabrique sous séquestre.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1914", fin="1918", libelle="Première Guerre mondiale",
             description="64 habitants de Pluherlin meurent pour la France.", commune="Pluherlin",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1926-02-06", fin="1926-02-06", libelle="Inauguration du monument aux morts",
             description="Monument aux morts inauguré au bourg.", commune="Pluherlin",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1939", fin="1945", libelle="Seconde Guerre mondiale",
             description="12 habitants de Pluherlin meurent pour la France.", commune="Pluherlin",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1944-06-24", fin="1944-06-24", libelle="Fusillade de réfractaires au STO",
             description="Huit réfractaires fusillés après les combats de Saint-Marcel ; le village de Carade est incendié.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1960", fin="1969", libelle="Fermeture des anciennes écoles publiques",
             description="Les écoles du bourg, devenues mixtes, sont fermées.", commune="Pluherlin",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1970", fin="1970", libelle="Dernière tentative de carrière d'ardoise",
             description="Tentative de remise en exploitation de la carrière du Pont de l'Église, sans succès.",
             commune="Pluherlin", departement="Morbihan", region="Bretagne"),
    ],
    "ploermel": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Ploërmel",
             description="Sous-préfecture du Morbihan.", commune="Ploërmel", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1793", libelle="Bataille de Ploërmel (Chouannerie)",
             description="Affrontements entre républicains et chouans.", commune="Ploërmel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1800", fin="2026", libelle="Sous-préfecture du Morbihan",
             description="Centre administratif et judiciaire du Porhoët.", commune="Ploërmel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1882", fin="1950", libelle="Tacot du Morbihan",
             description="Ploërmel est un nœud du réseau à voie étroite.", commune="Ploërmel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Ploërmel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Ploërmel",
             departement="Morbihan", region="Bretagne"),
    ],
    "rochefort_en_terre": [
        _evt(categorie="CULTURE", debut="1100", fin="2026", libelle="Cité médiévale de Rochefort-en-Terre",
             description="Château et bourg ; classé parmi les plus beaux villages de France.",
             commune="Rochefort-En-Terre", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Rochefort",
             description="Chef-lieu de canton et district en 1790.", commune="Rochefort-En-Terre",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1793", libelle="Prise du château par les chouans",
             description="Roche-des-Trois ; trois républicains tués lors de la prise du château.",
             commune="Rochefort-En-Terre", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1907", fin="1937", libelle="Restauration du château par Alfred Klots",
             description="Renaissance du site par la famille Klots.", commune="Rochefort-En-Terre",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1882", fin="1950", libelle="Desserte par le Tacot du Morbihan",
             description="La gare de Rochefort favorise l'activité du bourg.", commune="Rochefort-En-Terre",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Rochefort-En-Terre",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Rochefort-En-Terre",
             departement="Morbihan", region="Bretagne"),
    ],
    "vannes": [
        _evt(categorie="CULTURE", debut="0100", fin="0100", libelle="Cité gallo-romaine de Darioritum (Vannes)",
             description="Ancienne capitale des Venètes ; remparts et cathédrale.", commune="Vannes",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="2026", libelle="Préfecture du Morbihan",
             description="Vannes est le chef-lieu du département.", commune="Vannes",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Occupation de Vannes",
             description="Kommandantur et restrictions ; activité clandestine.", commune="Vannes",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="EVENEMENT", debut="1944", fin="1944", libelle="Libération de Vannes",
             description="Reprise de la préfecture à l'été 1944.", commune="Vannes",
             departement="Morbihan", region="Bretagne"),
    ],
    "rennes": [
        _evt(categorie="POLITIQUE", debut="1500", fin="1789", libelle="Siège du parlement de Bretagne",
             description="Rennes, capitale politique de la province.", commune="Rennes",
             departement="Ille-Et-Vilaine", region="Bretagne"),
        _evt(categorie="EVENEMENT", debut="1720", fin="1720", libelle="Grand incendie de Rennes",
             description="Destruction d'une grande partie du centre-ville.", commune="Rennes",
             departement="Ille-Et-Vilaine", region="Bretagne"),
        _evt(categorie="EVENEMENT", debut="1944", fin="1944", libelle="Libération de Rennes",
             description="Reprise de la ville le 4 août 1944.", commune="Rennes",
             departement="Ille-Et-Vilaine", region="Bretagne"),
    ],
    "paris": [
        _evt(categorie="EVENEMENT", debut="1789", fin="1789", libelle="Prise de la Bastille",
             description="Événement fondateur de la Révolution à Paris.", commune="Paris",
             departement="Paris", region="Île-de-France"),
        _evt(categorie="EVENEMENT", debut="1871", fin="1871", libelle="Commune de Paris",
             description="Insurrection et répression de mai 1871.", commune="Paris",
             departement="Paris", region="Île-de-France"),
        _evt(categorie="EVENEMENT", debut="1968", fin="1968", libelle="Mai 68 à Paris",
             description="Mouvement étudiant et grève générale.", commune="Paris",
             departement="Paris", region="Île-de-France"),
    ],
    "malestroit": [
        _evt(categorie="CULTURE", debut="1100", fin="2026", libelle="Bourg de Malestroit",
             description="Petite ville historique du Morbihan ; halles et patrimoine.", commune="Malestroit",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Malestroit",
             description="Bourg du Val de Vilaine, sur la route de Nantes à Brest.", commune="Malestroit",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur actif de la Chouannerie.", commune="Malestroit",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Malestroit",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Malestroit",
             departement="Morbihan", region="Bretagne"),
    ],
    "questembert": [
        _evt(categorie="CULTURE", debut="1552", fin="1552", libelle="Premières Halles de Questembert",
             description="Première mention attestée des Halles, cœur du commerce local.", commune="Questembert",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1675", fin="1675", libelle="Reconstruction des Halles",
             description="Reconstruction des Halles ; la charpente monumentale est encore visible aujourd'hui.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1719", fin="1719", libelle="Conspiration de Pontcallec",
             description="Environ 200 gentilshommes et paysans se rassemblent à Kérédren avant l'échec du soulèvement.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1724", fin="1787", libelle="Missions paroissiales des Lazaristes",
             description="Grandes missions prêchées en 1724, 1737, 1749, 1763, 1775 et 1787.", commune="Questembert",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1789", fin="1789", libelle="Cahier de doléances",
             description="Rédaction du cahier de doléances et participation aux débuts de la Révolution.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Questembert",
             description="Création officielle de la commune dans le nouveau département du Morbihan.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1791", fin="1791", libelle="Constitution civile du clergé",
             description="Application de la loi ; fortes tensions religieuses dans la commune.", commune="Questembert",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1793", libelle="Combat de Coët-Bihan",
             description="Important affrontement entre républicains et chouans sur le territoire de Questembert.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1796", libelle="Chouannerie à Questembert",
             description="Foyer actif de la Chouannerie ; presbytère réquisitionné par les républicains puis incendié par les chouans.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1801", fin="1801", libelle="Réorganisation religieuse du Concordat",
             description="Reprise progressive de la vie paroissiale après le Concordat.", commune="Questembert",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1845-04-13", fin="1845-04-13", libelle="Rachat des Halles par la municipalité",
             description="La commune rachète les Halles, auparavant propriété privée.", commune="Questembert",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1862", fin="1862", libelle="Gare de Questembert",
             description="Mise en service sur la ligne Savenay–Landerneau ; essor des échanges commerciaux.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1880", fin="1899", libelle="Commerce des grains et foires",
             description="Développement du commerce des grains, foires et marchés dans le sud-est du Morbihan.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1914", fin="1918", libelle="Première Guerre mondiale",
             description="192 habitants de Questembert meurent pour la France.", commune="Questembert",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1922-09-18", fin="1922-09-18", libelle="Classement Monuments historiques",
             description="Les Halles, la chapelle Saint-Michel et plusieurs monuments sont classés.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1939", fin="1944", libelle="Occupation et Résistance",
             description="La gare de Bel-Air sert au passage d'aviateurs alliés évadés grâce à la Résistance.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
        _evt(categorie="EVENEMENT", debut="1944", fin="1944", libelle="Libération de Questembert",
             description="Plusieurs résistants tués ou déportés ; libération durant l'été 1944.", commune="Questembert",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1950", fin="1970", libelle="Modernisation agricole",
             description="Mécanisation et transformation progressive de l'économie rurale.", commune="Questembert",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="2005", fin="2005", libelle="Chevaux de trait bretons au service public",
             description="Introduction de chevaux territoriaux pour certaines missions de service public.",
             commune="Questembert", departement="Morbihan", region="Bretagne"),
    ],
    "pleucadeuc": [
        _evt(categorie="CULTURE", debut="1500", fin="1599", libelle="Paroisse et manoirs nobles",
             description="Dépendance du diocèse de Vannes ; manoirs de La Cour, Le Plessis, etc.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1532", fin="1532", libelle="Rattachement de la Bretagne au royaume de France",
             description="La paroisse devient partie du royaume de France.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1550", fin="1580", libelle="Demeures nobles",
             description="Reconstruction ou agrandissement de plusieurs demeures nobles de la paroisse.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1590", fin="1598", libelle="Guerres de Religion",
             description="Troubles dans la région ; circulation de troupes dans le pays de Malestroit.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1600", fin="1650", libelle="Agriculture céréalière et élevage",
             description="Développement de l'agriculture céréalière et de l'élevage au XVIIe siècle.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1630", fin="1660", libelle="Cultures du lin et du chanvre",
             description="Essor des cultures du lin et du chanvre dans le secteur.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1675", fin="1675", libelle="Révolte des Bonnets rouges",
             description="Agitation fiscale dans la région de Malestroit.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1690", fin="1699", libelle="Restauration de chapelles et calvaires",
             description="Restauration de chapelles et de calvaires paroissiaux en fin de XVIIe siècle.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1700", fin="1750", libelle="Croissance démographique",
             description="La paroisse compte environ 1 500 à 2 000 habitants au début du XVIIIe siècle.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1750", fin="1780", libelle="Travaux sur l'église paroissiale",
             description="Entretien de l'église paroissiale et des chapelles.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1789", fin="1789", libelle="Cahier de doléances",
             description="Rédaction du cahier de doléances de Pleucadeuc.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Pleucadeuc",
             description="Création officielle de la commune lors de la Révolution française.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1791", fin="1791", libelle="Serment constitutionnel du clergé",
             description="Réorganisation administrative et religieuse ; tensions autour du serment.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Insurrection royaliste affectant tout le Morbihan intérieur.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1801", fin="1801", libelle="Réorganisation religieuse du Concordat",
             description="Réorganisation religieuse après le Concordat.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1820", fin="1840", libelle="Modernisation des routes",
             description="Amélioration des routes vers Malestroit et Ruffiac.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1832", fin="1832", libelle="Troubles légitimistes",
             description="Agitation liée à l'insurrection de la duchesse de Berry dans la région.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="Épidémie touchant le pays de Malestroit et Pleucadeuc.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1854", fin="1854", libelle="Épidémie de dysenterie",
             description="Épidémie signalée dans plusieurs communes voisines.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1860", fin="1870", libelle="Travaux sur l'église paroissiale",
             description="Travaux importants sur l'église paroissiale.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1870", fin="1871", libelle="Guerre franco-prussienne",
             description="Mobilisation des habitants.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1871", fin="1871", libelle="Épidémie de variole",
             description="Épidémie de variole dans le secteur.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1880", fin="1890", libelle="Foires et commerce agricole",
             description="Développement des foires et du commerce agricole local.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="1905", fin="1905", libelle="Séparation des Églises et de l'État",
             description="Inventaires des biens religieux.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1914", fin="1918", libelle="Première Guerre mondiale",
             description="Nombreux morts au front parmi les habitants.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1920", fin="1920", libelle="Monument aux morts",
             description="Inauguration du monument aux morts.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1920", fin="1929", libelle="Arrivée de l'électricité",
             description="Électrification progressive de la commune dans les années 1920.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1939", fin="1945", libelle="Seconde Guerre mondiale",
             description="Occupation allemande et mobilisation locale.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="EVENEMENT", debut="1944", fin="1944", libelle="Libération de Pleucadeuc",
             description="Libération de la commune.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1950", fin="1959", libelle="Mécanisation agricole",
             description="Mécanisation de l'agriculture dans les années 1950.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1960", fin="1969", libelle="Réseau d'eau potable",
             description="Extension du réseau d'eau potable dans les années 1960.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1970", fin="1979", libelle="Remembrement agricole",
             description="Remembrement agricole dans les années 1970.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1980", fin="1989", libelle="Zones artisanales et services",
             description="Développement des zones artisanales et des services dans les années 1980.",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1990", fin="1999", libelle="Croissance résidentielle",
             description="Développement résidentiel autour du bourg.", commune="Pleucadeuc",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="EVENEMENT", debut="1994", fin="2019", libelle="Rassemblement des « Deux et plus »",
             description="Chaque 15 août, rencontre nationale de jumeaux et triplés ; « village des Jumeaux ».",
             commune="Pleucadeuc", departement="Morbihan", region="Bretagne"),
    ],
    "malansac": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Malansac",
             description="Paroisse du pays de Rochefort.", commune="Malansac", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="0847", fin="1100", libelle="Paroisse et fondations religieuses",
             description="Mentions au cartulaire de Redon ; prieurés de la Mongée et couvent des Cordeliers de Bodelio.",
             commune="Malansac", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur de la châtellenie de Rochefort, prise du château par les chouans en 1793.",
             commune="Malansac", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1750", fin="1920", libelle="Poterie de Malansac",
             description="Production céramique réputée ; l'une des rares en Bretagne sud.", commune="Malansac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1862", fin="1950", libelle="Gare de Malansac",
             description="Ligne Rennes–Redon puis Tacot du Morbihan.", commune="Malansac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Malansac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Malansac",
             departement="Morbihan", region="Bretagne"),
    ],
    "la_chapelle_launay": [
        _evt(categorie="CULTURE", debut="1161", fin="2026", libelle="Abbaye de Blanche-Couronne",
             description="Abbaye bénédictine fondée au XIIe siècle ; moines jusqu'à la Révolution.",
             commune="La Chapelle-Launay", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de La Chapelle-Launay",
             description="Capella de Alneto ; deux seigneuries (Mareil et Blanche-Couronne).",
             commune="La Chapelle-Launay", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1793-12-23", fin="1793-12", libelle="Derniers combats vendéens",
             description="Après Savenay, résistance des survivants vendéens dans les bois de Blanche-Couronne.",
             commune="La Chapelle-Launay", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="La Chapelle-Launay",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="La commune reste dans la poche allemande jusqu'au 11 mai 1945.",
             commune="La Chapelle-Launay", departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
    "la_gacilly": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de La Gacilly",
             description="Ancienne trève de Carentoir ; chef-lieu de canton.", commune="La Gacilly",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1959", fin="1959", libelle="Création d'Yves Rocher à La Gacilly",
             description="Naissance de l'entreprise cosmétique ; essor économique local.",
             commune="La Gacilly", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="2003", fin="2026", libelle="Festival Photo La Gacilly",
             description="Expositions en plein air ; renommée culturelle.", commune="La Gacilly",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="La Gacilly",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="La Gacilly",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="La Gacilly",
             departement="Morbihan", region="Bretagne"),
    ],
    "groix": [
        _evt(categorie="CULTURE", debut="1500", fin="2026", libelle="Île de Groix",
             description="Commune insulaire ; pêche et maritime.", commune="Groix",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="EVENEMENT", debut="1909", fin="1909", libelle="Grève des pêcheurs groisillons",
             description="Conflit social majeur sur l'île.", commune="Groix",
             departement="Morbihan", region="Bretagne"),
    ],
    "monteneuf": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Monteneuf",
             description="Commune des landes de Monteneuf.", commune="Monteneuf",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1836", fin="1836", libelle="Rattachement de la Grée de Callac",
             description="Territoire d'Augan transféré à Monteneuf.", commune="Monteneuf",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1986", fin="2026", libelle="Site mégalithique des Landes de Monteneuf",
             description="Alignements de menhirs remis en valeur.", commune="Monteneuf",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="Monteneuf",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Monteneuf",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Monteneuf",
             departement="Morbihan", region="Bretagne"),
    ],
    "concoret": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Concoret",
             description="Porte de la forêt de Paimpont (Brocéliande).", commune="Concoret",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1800", fin="2026", libelle="Forêt de Paimpont et légende arthurienne",
             description="Commune associée à la légende de Brocéliande.", commune="Concoret",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="Concoret",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Concoret",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Concoret",
             departement="Morbihan", region="Bretagne"),
    ],
    "molac": [
        _evt(categorie="CULTURE", debut="1100", fin="2026", libelle="Baronnie de Molac",
             description="Ancien centre seigneurial du Morbihan.", commune="Molac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Molac",
             description="Bourg du pays de Vannes.", commune="Molac", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur du Porhoët touché par la Chouannerie.", commune="Molac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Molac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Molac",
             departement="Morbihan", region="Bretagne"),
    ],
    "guer": [
        _evt(categorie="CULTURE", debut="1200", fin="2026", libelle="Collégiale Saint-Pierre de Guer",
             description="Édifice religieux majeur du secteur.", commune="Guer",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Guer",
             description="Bourg du pays de Vannes, ancien centre seigneurial.", commune="Guer",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur actif de la Chouannerie.", commune="Guer",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Guer",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Guer",
             departement="Morbihan", region="Bretagne"),
    ],
    "savenay": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Savenay",
             description="Bourg du pays nantais, sur la Loire.", commune="Savenay",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1793-12-23", fin="1793-12-23", libelle="Bataille de Savenay",
             description="Défaite vendéenne ; fin de l'armée catholique et royale.", commune="Savenay",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Savenay",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="Savenay reste dans la poche allemande jusqu'au 11 mai 1945.", commune="Savenay",
             departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
    "donges": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Donges",
             description="Commune de l'estuaire de la Loire.", commune="Donges",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="SCIENCE", debut="1975", fin="2026", libelle="Raffinerie de Donges",
             description="Grand site industriel pétrolier sur l'estuaire.", commune="Donges",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Donges",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="Donges reste dans la poche allemande jusqu'au 11 mai 1945.", commune="Donges",
             departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
    "pontchateau": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Pontchâteau",
             description="Baronnie et carrefour du pays de Blain.", commune="Pontchâteau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="CULTURE", debut="1883", fin="1905", libelle="Basilique Saint-Gilles de Pontchâteau",
             description="Construction d'un important sanctuaire breton.", commune="Pontchâteau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1793", fin="1796", libelle="Guerres civiles de l'Ouest",
             description="Chouannerie et troubles révolutionnaires.", commune="Pontchâteau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Pontchâteau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="Pontchâteau reste dans la poche allemande jusqu'au 11 mai 1945.", commune="Pontchâteau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
    "prinquiau": [
        _evt(categorie="CULTURE", debut="1090", fin="1500", libelle="Origines : Prehinquel / Prinqueleau",
             description="« Proche de l'eau » ; la Loire atteignait autrefois le bourg.", commune="Prinquiau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Prinquiau",
             description="Commune rurale entre Brière et Sillon de Bretagne.", commune="Prinquiau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="CULTURE", debut="1385", fin="1603", libelle="Château de l'Escurays",
             description="Manoir médiéval puis Renaissance ; motte féodale possible dès le IXe siècle.",
             commune="Prinquiau", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="POLITIQUE", debut="1771", fin="1771", libelle="Société Debray pour l'assèchement des marais",
             description="Projet d'assèchement des marais de la commune.", commune="Prinquiau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1793-12", fin="1793-12", libelle="Bataille de Savenay et refuge vendéen",
             description="Survivants vendéens se cachent dans les bois ; tombe des ossements à Sem.",
             commune="Prinquiau", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1793-12-22", fin="1793-12-23", libelle="Refuge de Mme de Lescure à l'Escurays",
             description="La marquise de La Rochejacquelein se réfugie au château après Savenay.",
             commune="Prinquiau", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Prinquiau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="Prinquiau reste dans la poche allemande jusqu'au 11 mai 1945.", commune="Prinquiau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="CULTURE", debut="1994", fin="2026", libelle="Rachat du château par la commune",
             description="L'Escurays est acquis par la mairie ; restauration patrimoniale.", commune="Prinquiau",
             departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
    "serent": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Sérent",
             description="Commune rurale du centre Morbihan.", commune="Sérent",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1500", fin="2026", libelle="Bourg de Sérent",
             description="Carrefour rural entre Ploërmel et Vannes.", commune="Sérent",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="Sérent",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Sérent",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Sérent",
             departement="Morbihan", region="Bretagne"),
    ],
    "saint_congard": [
        _evt(categorie="CULTURE", debut="0820", fin="0820", libelle="Donation du machtiern de Pleucadeuc à Roga",
             description="Cartulaire de Redon ; ermitage sur le territoire actuel de Saint-Congard.",
             commune="Saint-Congard", departement="Morbihan", region="Bretagne"),
        _evt(categorie="POLITIQUE", debut="0848", fin="0849", libelle="Synode de Nominoë à Coët-Leu",
             description="Assemblée religieuse et politique du duc Nominoë au lieu-dit Coët-Leu de Bas.",
             commune="Saint-Congard", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1100", fin="1100", libelle="Détachement de la paroisse de Pleucadeuc",
             description="Saint-Congard devient paroisse distincte au XIIe siècle.", commune="Saint-Congard",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Saint-Congard",
             description="Commune du Val de Vilaine ; canton de Rochefort-en-Terre en 1801.",
             commune="Saint-Congard", departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1840", fin="1977", libelle="Canal de Nantes à Brest et écluses",
             description="Écluses de Beaumont, Foveno et Rieux ; dernière péniche commerciale en 1977.",
             commune="Saint-Congard", departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Saint-Congard",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance dans le Val de Vilaine.", commune="Saint-Congard",
             departement="Morbihan", region="Bretagne"),
    ],
    "campbon": [
        _evt(categorie="CULTURE", debut="0500", fin="0700", libelle="Pèlerinage à Saint-Victor",
             description="Ermite du VIe ou VIIe siècle ; occupation gallo-romaine attestée.", commune="Campbon",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Campbon",
             description="Châtellenie démembrée de la baronnie de Pontchâteau.", commune="Campbon",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="POLITIQUE", debut="1565", fin="1663", libelle="Seigneurs du Cambout et duché de Coislin",
             description="Acquisition par les du Cambout ; marquisat puis duché-pairie en 1663.",
             commune="Campbon", departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Tensions révolutionnaires et mémoire chouanne dans la commune.", commune="Campbon",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Campbon",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="Campbon reste dans la poche allemande jusqu'au 11 mai 1945.", commune="Campbon",
             departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
    "carentoir": [
        _evt(categorie="CULTURE", debut="0100", fin="0500", libelle="Voie romaine et occupation antique",
             description="Voie Ahès (Angers–Carhaix) ; vestiges gallo-romains sur la butte de Marsac.",
             commune="Carentoir", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1100", fin="1790", libelle="Paroisse primitive de Carentoir",
             description="Territoire englobant La Gacilly, Quelneuc, Ruffiac, Le Temple et d'autres trèves.",
             commune="Carentoir", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Carentoir",
             description="Chef-lieu ecclésiastique du canton.", commune="Carentoir",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1796", libelle="Persécutions religieuses",
             description="Arrestation du doyen Le Cerf en 1796 ; vente du prieuré du Temple.",
             commune="Carentoir", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1863", fin="1863", libelle="Création de la commune de Quelneuc",
             description="Quelneuc est détaché de Carentoir.", commune="Carentoir",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Carentoir",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Libération le 3 août 1944.", commune="Carentoir",
             departement="Morbihan", region="Bretagne"),
    ],
    "allaire": [
        _evt(categorie="CULTURE", debut="0878", fin="0878", libelle="Couronne ducale d'Alain le Grand",
             description="Alain le Grand reçoit la couronne de Bretagne dans l'église d'Allaire.",
             commune="Allaire", departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1100", fin="1790", libelle="Paroisse primitive d'Allaire",
             description="Territoire englobant Béganne, Rieux, Saint-Jean-la-Poterie et Saint-Gorgon.",
             commune="Allaire", departement="Morbihan", region="Bretagne"),
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune d'Allaire",
             description="Bourg du pays de Redon, sur la route Vannes–Redon.", commune="Allaire",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="Allaire",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Allaire",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Allaire",
             departement="Morbihan", region="Bretagne"),
    ],
    "saint_marcel": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Saint-Marcel",
             description="Commune du pays de Redon, au confluent de l'Oust et de la Vilaine.", commune="Saint-Marcel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1835", fin="1960", libelle="Port et activité fluviale",
             description="Port sur l'Oust ; écluses et commerce fluvial vers Redon et Nantes.",
             commune="Saint-Marcel", departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur du Porhoët touché par la Chouannerie.", commune="Saint-Marcel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Saint-Marcel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Saint-Marcel",
             departement="Morbihan", region="Bretagne"),
    ],
    "caden": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Caden",
             description="Paroisse de la châtellenie de Rochefort.", commune="Caden",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Juridiction des seigneurs de Rochefort ; secteur actif.", commune="Caden",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Caden",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Caden",
             departement="Morbihan", region="Bretagne"),
    ],
    "beignon": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Beignon",
             description="Ancienne trève de la paroisse d'Allaire.", commune="Beignon",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="Beignon",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Beignon",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Beignon",
             departement="Morbihan", region="Bretagne"),
    ],
    "caro": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Caro",
             description="Commune du pays de Vannes, au sud du Morbihan.", commune="Caro",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="CULTURE", debut="1100", fin="2026", libelle="Chapelle et calvaires",
             description="Patrimoine religieux rural du Porhoët.", commune="Caro",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="Caro",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Caro",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Caro",
             departement="Morbihan", region="Bretagne"),
    ],
    "bohal": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Bohal",
             description="Petite commune rurale du centre Morbihan.", commune="Bohal",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur du Porhoët touché par la Chouannerie.", commune="Bohal",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Bohal",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Bohal",
             departement="Morbihan", region="Bretagne"),
    ],
    "limerzel": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Limerzel",
             description="Paroisse de la châtellenie de Rochefort.", commune="Limerzel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="SCIENCE", debut="1882", fin="1950", libelle="Desserte par le Tacot du Morbihan",
             description="Ligne à voie étroite du réseau morbihannais.", commune="Limerzel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur de Rochefort touché par la Chouannerie.", commune="Limerzel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Limerzel",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Limerzel",
             departement="Morbihan", region="Bretagne"),
    ],
    "ruffiac": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Ruffiac",
             description="Ancienne trève de la paroisse de Carentoir.", commune="Ruffiac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="Ruffiac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Ruffiac",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Ruffiac",
             departement="Morbihan", region="Bretagne"),
    ],
    "peaule": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Péaule",
             description="Paroisse de la châtellenie de Rochefort, proche de l'estuaire.", commune="Péaule",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur de Rochefort touché par la Chouannerie.", commune="Péaule",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Péaule",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Péaule",
             departement="Morbihan", region="Bretagne"),
    ],
    "larre": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Larré",
             description="Commune rurale du centre Morbihan.", commune="Larré",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Mobilisation royaliste dans les campagnes.", commune="Larré",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Larré",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Larré",
             departement="Morbihan", region="Bretagne"),
    ],
    "monterrein": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Monterrein",
             description="Commune rurale du Porhoët.", commune="Monterrein",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1793", fin="1800", libelle="Chouannerie",
             description="Secteur du Porhoët touché par la Chouannerie.", commune="Monterrein",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Monterrein",
             departement="Morbihan", region="Bretagne"),
        _evt(categorie="GUERRE", debut="1940", fin="1944", libelle="Seconde Guerre mondiale",
             description="Occupation et résistance locale.", commune="Monterrein",
             departement="Morbihan", region="Bretagne"),
    ],
    "crossac": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Crossac",
             description="Commune du canton de Pontchâteau, pays nantais.", commune="Crossac",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1793", fin="1796", libelle="Guerres civiles de l'Ouest",
             description="Chouannerie dans le pays nantais.", commune="Crossac",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Crossac",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="Crossac reste dans la poche allemande jusqu'au 11 mai 1945.", commune="Crossac",
             departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
    "bouvron": [
        _evt(categorie="ADMINISTRATION", debut="1790", fin="1790", libelle="Création de la commune de Bouvron",
             description="Commune du pays de Blain, Brière nord.", commune="Bouvron",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1793", fin="1796", libelle="Guerres civiles de l'Ouest",
             description="Chouannerie dans le pays nantais.", commune="Bouvron",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="PANDEMIE", debut="1849", fin="1850", libelle="Épidémie de choléra",
             description="La commune subit la seconde grande vague de choléra.", commune="Bouvron",
             departement="Loire-Atlantique", region="Pays de la Loire"),
        _evt(categorie="GUERRE", debut="1944-08", fin="1945-05-11", libelle="Poche de Saint-Nazaire",
             description="Bouvron reste dans la poche allemande jusqu'au 11 mai 1945.", commune="Bouvron",
             departement="Loire-Atlantique", region="Pays de la Loire"),
    ],
}

TACOT_SLUGS = {
    "pluherlin", "rochefort_en_terre", "limerzel", "malansac", "peillac",
    "saint_grave", "saint_jacut_les_pins", "campeneac", "augan",
}


def build_events(meta: dict) -> list[dict]:
    slug = meta["slug"]
    if slug in CUSTOM:
        events = list(CUSTOM[slug])
    else:
        events = base_events(meta)

    if slug in TACOT_SLUGS and slug not in CUSTOM:
        events.append(
            _evt(
                categorie="SCIENCE",
                debut="1882",
                fin="1950",
                libelle="Desserte par le Tacot du Morbihan",
                description="Ligne à voie étroite du réseau morbihannais.",
                commune=meta["commune"],
                departement=meta.get("departement"),
                region=meta.get("region"),
            )
        )

    events.sort(key=lambda e: (e["debut"], e["fin"], e["libelle"]))
    return events


def main() -> None:
    index_path = COMMUNAL_DIR / "_index.json"
    if not index_path.is_file():
        raise SystemExit(f"Index introuvable : {index_path}")

    communes = json.loads(index_path.read_text(encoding="utf-8"))
    for meta in communes:
        slug = meta["slug"]
        path = COMMUNAL_DIR / f"{slug}.json"
        events = build_events(meta)
        path.write_text(
            json.dumps(events, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

    print(f"{len(communes)} fichiers communal alimentés dans {COMMUNAL_DIR}")


if __name__ == "__main__":
    main()
